#!/usr/bin/env bash

# Common bash functions.
# Copyright (C) 2005 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eu

function run() {
    docker run -i --rm 1121citrus/ha-bash-base:1.1.0 "${@}"
}

status=0

#### current-month()
# Returns the current month as a 2 digit (leading zero) integer.

[[ $(run current-month) == $(date +%m) ]] || { echo current-month failed; status=1; }


#### current-year()
# Returns the current year as a 4 digit integer.

[[ $(run current-year) == $(date +%Y) ]] || { echo current-year failed; status=1; }


#### day-of-month()
# Returns the date in the current month as a 2 digit (leading zero) integer.

[[ $(run day-of-month) == $(date +%d) ]] || { echo day-of-month failed; status=1; }


#### today()
# Returns the date in YYYY-MM-DD format.

[[ $(run today) == $(date +%Y-%m-%d) ]] || { echo today failed; status=1; }


#### tomorrow()
# Returns the tomorrow's date in YYYY-MM-DD format.

[[ $(run tomorrow) == $(date -d tomorrow +%Y-%m-%d) ]] || { echo tomorrow failed; status=1; }


#### yesterday()
# Returns the yesterday's date in YYYY-MM-DD format.

[[ $(run yesterday) == $(date -d yesterday +%Y-%m-%d) ]] || { echo yesterday failed; status=1; }


exit $status

