#!/usr/bin/env bash

# Common bash functions.
# Copyright (C) 2005 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eu

function run() {
    docker run -i --rm 1121citrus/ha-bash-base:1.1.0 "${@}"
}

status=0


#### debug()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 debug 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[DEBUG\]\ message ]] || { echo debug failed; status=1; }


#### dryrun()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 dryrun 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[DRYRUN\]\ message ]] || { echo dryrun failed; status=1; }


#### error()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 error 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[ERROR\]\ message ]] || { echo error failed; status=1; }


#### ignore()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 ignore 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[IGNORE\]\ message ]] || { echo ignore failed; status=1; }


#### info()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 info 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[INFO\]\ message ]] || { echo info failed; status=1; }


#### warn()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 warn 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[WARN\]\ message ]] || { echo warn failed; status=1; }


#### warning()

[[ $(echo message | docker run -i --rm 1121citrus/ha-bash-base:1.1.0 warning 2>&1 ) =~ ^2[0-9]{3}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])T(0[1-9]|1[0-9]|2[0-3])(0[1-9]|[1-5][0-9]){2}\ bash\ \[WARN\]\ message ]] || { echo warn failed; status=1; }


exit $status


