#!/usr/bin/env bash

# Yet another version of `rotate-backups` but this time applied to an AWS S3 backup archive bucket.
# Copyright (C) 2005 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function __log() {
    local severity=${1:?Need severity}
    shift
    echo $(date '+%Y%m%dT%H%M%S') $(basename "${0}") [${severity}] "${@:-}" >/dev/stderr
}

function log() {
    local severity=${1:?Need severity}
    shift
    if [[ -n "${@:-}" ]]; then
        (set -o noglob; __log "${severity}" "${@}")
    else
        while read line; do
            (set -o noglob; __log "${severity}" ${line})
        done
    fi
}

function debug() {
    (set -o noglob; log DEBUG "${@:-}")
}

function error() {
    (set -o noglob; log ERROR "${@:-}")
    exit ${EXIT_CODE:-1}
}

function ignore() {
    (set -o noglob; log IGNORE "${@:-}")
}

function info() {
    (set -o noglob; log INFO "${@:-}")
}

function is_false() {
    ! is_true "${@}"
}

function is_true() {
    if [[ "${#@}" = "0" ]]; then cat /dev/stdin | head -n 1; else echo "${1}"; fi | grep -E -i -q '^\s*(1|true|t|yes|y)\s*$' >/dev/null 2>&1
}

function tolower() {
    # FIXME: support unicode
    tr '[A-Z]' '[a-z]'
}

function toupper() {
    # FIXME: support unicode
    tr '[a-z]' '[A-Z]'
}

function warn() {
    (set -o noglob; log WARN "${@:-}")
}

function warning() {
    (set -o noglob; warn "${@:-}")
}

