#!/usr/bin/env bash

# Common bash functions.
# Copyright (C) 2005 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function current-month() {
    date "+%m"
}

function current-year() {
    date "+%Y"
}

function day-in-year() {
    php -r 'date_default_timezone_set("UTC"); $a = date("z", time()); echo $a;'
}

function day-of-month() {
    date "+%d"
}

function today() {
    date "+%Y-%m-%d"
}

function tomorrow() {
    date "+%Y-%m-%d" --date=tomorrow
}

function yesterday() {
    date "+%Y-%m-%d" --date=yesterday
}

# function ytd-dates() {
#     for f in $(seq 1 $(day-in-year) | tail -r); do
#         eval "date -v-${f}d '+%Y-%m-%d'"
#     done
# }

