#!/usr/bin/env bash

# Common bash setup.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

whereami=$(dirname $(readlink -f "${BASH_SOURCE}"))
BASH_FUNCTION_DIR=${BASH_FUNCTION_DIR:-$(cd "${whereami}" && pwd)}
BIN_DIR=${BIN_DIR:-$(cd "${BASH_FUNCTION_DIR}/../../bin" && pwd)}

source "${COMMON_FUNCTIONS_FILE:-${BASH_FUNCTION_DIR}/common-functions}"

path-prepend "${BIN_DIR}"
