#!/usr/bin/env bash

# Common bash functions.
# Copyright (C) 2005 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function md5() {
    md5sum | awk '{print $1}'
}

function sha1() {
    shasum -a1 | awk '{print $1}'
}

function sha224() {
    shasum -a224 | awk '{print $1}'
}

function sha256() {
    shasum -a256 | awk '{print $1}'
}

function sha384() {
    shasum -a384 | awk '{print $1}'
}

function sha512() {
    shasum -a512 | awk '{print $1}'
}

function sha512-224() {
    shasum -a512224 | awk '{print $1}'
}

function sha512-256() {
    shasum -a512256 | awk '{print $1}'
}
