#!/usr/bin/env bash

# Common bash functions.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


function path-append() {
    export PATH=$(echo "${PATH}" | __path-element-append "$1")
}

function path-prepend() {
    export PATH=$(echo "${PATH}" | __path-element-prepend "$1")
}

function path-remove() {
    export PATH=$(echo "${PATH}" | __path-element-remove "$1")
}

function __path-element-append() {
    echo $(__path-element-remove "$1"):"${1}"
}

function __path-element-prepend() {
    echo "${1}":$(__path-element-remove "$1")
}

function __path-element-remove() {
    sed "s|:${1}:|:|g" | sed "s|^${1}:||"  | sed "s|:${1}$||"
}

